# Generated by Django 5.1.7 on 2025-09-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ['codigo'], 'verbose_name': 'Unidade Organizacional', 'verbose_name_plural': 'Unidades Organizacionais'},
        ),
        migrations.RemoveIndex(
            model_name='unidade',
            name='unidades_codigo__951deb_idx',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='codigo_interno',
        ),
        migrations.AddField(
            model_name='unidade',
            name='codigo',
            field=models.CharField(default='temp', help_text='Código hierárquico da unidade (ex: 1.2.01.20.01.101)', max_length=50, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidade',
            name='codigo_allstrategy',
            field=models.CharField(blank=True, help_text='Código original/interno da unidade (ex: 101, 102, etc)', max_length=20, verbose_name='Código All Strategy'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['codigo'], name='unidades_codigo_a2b9f8_idx'),
        ),
    ]
