# Generated by Django 5.1.7 on 2025-09-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_unidade_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='responsavel',
        ),
    ]
