# Generated by Django 5.1.7 on 2025-09-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_unidade_responsavel'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='unidade',
            name='unidades_tipo_2644e4_idx',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='tipo',
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['ativa'], name='unidades_ativa_6fd9a8_idx'),
        ),
    ]
