# Generated by Django 5.1.7 on 2025-09-04 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_unidade_unidades_tipo_2644e4_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['codigo'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='logo',
        ),
        migrations.AddField(
            model_name='empresa',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='data_ultima_sincronizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=30, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='matriz',
            field=models.BooleanField(default=False, help_text='Marque se esta é a empresa matriz do grupo', verbose_name='Matriz'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sincronizado_allstrategy',
            field=models.BooleanField(default=False, verbose_name='Sincronizado All Strategy'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(help_text='CNPJ da empresa (formato: XX.XXX.XXX/XXXX-XX)', max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codigo',
            field=models.CharField(help_text='Código numérico de 2 dígitos (ex: 01, 02, 10)', max_length=2, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=30, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['codigo'], name='empresas_codigo_814239_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['cnpj'], name='empresas_cnpj_009d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['ativa'], name='empresas_ativa_ae071f_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['matriz'], name='empresas_matriz_f05540_idx'),
        ),
    ]
