# Generated by Django 5.1.7 on 2025-09-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_empresa_options_remove_empresa_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['sigla'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RemoveIndex(
            model_name='empresa',
            name='empresas_codigo_814239_idx',
        ),
        migrations.RemoveIndex(
            model_name='empresa',
            name='empresas_matriz_f05540_idx',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='matriz',
        ),
        migrations.AddField(
            model_name='empresa',
            name='sigla',
            field=models.CharField(default='EMP', max_length=15, primary_key=True, serialize=False, verbose_name='Sigla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['sigla'], name='empresas_sigla_c60b15_idx'),
        ),
    ]
