# Generated by Django 5.1.7 on 2025-09-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='codigo_allstrategy',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código All Strategy'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nivel',
            field=models.IntegerField(verbose_name='Nível Hierárquico'),
        ),
    ]
