# Generated by Django 5.1.7 on 2025-09-04 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_unidade_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='empresa',
            field=models.ForeignKey(default='CMC', on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='core.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['empresa'], name='unidades_empresa_2d6101_idx'),
        ),
    ]
