# Generated by Django 5.1.7 on 2025-09-04 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_unidade_empresa_unidade_unidades_empresa_2d6101_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='core.empresa', verbose_name='Empresa'),
        ),
    ]
