# Generated by Django 5.1.7 on 2025-09-04 12:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_unidade_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrocusto',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='contacontabil',
            name='aceita_lancamento',
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='centro_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_centros', to='core.centrocusto', verbose_name='Centro de Custo Superior'),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='nivel',
            field=models.IntegerField(default=1, verbose_name='Nível Hierárquico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='tipo_operacional',
            field=models.CharField(choices=[('operacional', 'Operacional'), ('administrativo', 'Administrativo'), ('comercial', 'Comercial'), ('financeiro', 'Financeiro'), ('ti', 'Tecnologia da Informação'), ('rh', 'Recursos Humanos'), ('projeto', 'Projeto Específico')], default='operacional', max_length=50, verbose_name='Tipo Operacional'),
        ),
        migrations.AddField(
            model_name='contacontabil',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contacontabil',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Centro de Custo'),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='orcamento_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Orçamento Anual'),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='orcamento_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Orçamento Mensal'),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_custo_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centros_custo', to='core.unidade', verbose_name='Unidade Vinculada'),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='categoria_dre',
            field=models.CharField(blank=True, help_text='Ex: Receita Bruta, CMV, Despesas Operacionais', max_length=100, verbose_name='Categoria DRE'),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='conta_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontas', to='core.contacontabil', verbose_name='Conta Superior'),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='nivel',
            field=models.IntegerField(verbose_name='Nível Hierárquico'),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da Conta'),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='subcategoria_dre',
            field=models.CharField(blank=True, help_text='Ex: Vendas, Material, Pessoal', max_length=100, verbose_name='Subcategoria DRE'),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='tipo_conta',
            field=models.CharField(choices=[('receita', 'Receita'), ('custo', 'Custo'), ('despesa', 'Despesa'), ('ativo', 'Ativo'), ('passivo', 'Passivo'), ('patrimonio', 'Patrimônio Líquido')], max_length=50, verbose_name='Tipo da Conta'),
        ),
        migrations.AddIndex(
            model_name='centrocusto',
            index=models.Index(fields=['codigo'], name='centros_cus_codigo_0e4605_idx'),
        ),
        migrations.AddIndex(
            model_name='centrocusto',
            index=models.Index(fields=['ativo'], name='centros_cus_ativo_91328b_idx'),
        ),
        migrations.AddIndex(
            model_name='centrocusto',
            index=models.Index(fields=['centro_pai', 'ativo'], name='centros_cus_centro__ec3b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='centrocusto',
            index=models.Index(fields=['nivel'], name='centros_cus_nivel_d0d45a_idx'),
        ),
        migrations.AddIndex(
            model_name='centrocusto',
            index=models.Index(fields=['unidade'], name='centros_cus_unidade_275ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='contacontabil',
            index=models.Index(fields=['codigo'], name='contas_cont_codigo_c596a6_idx'),
        ),
        migrations.AddIndex(
            model_name='contacontabil',
            index=models.Index(fields=['ativa'], name='contas_cont_ativa_295a30_idx'),
        ),
        migrations.AddIndex(
            model_name='contacontabil',
            index=models.Index(fields=['conta_pai', 'ativa'], name='contas_cont_conta_p_af60cf_idx'),
        ),
        migrations.AddIndex(
            model_name='contacontabil',
            index=models.Index(fields=['nivel'], name='contas_cont_nivel_2efcbe_idx'),
        ),
        migrations.AddIndex(
            model_name='contacontabil',
            index=models.Index(fields=['tipo_conta'], name='contas_cont_tipo_co_d07845_idx'),
        ),
    ]
