# Generated by Django 5.1.7 on 2025-09-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_centrocusto_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='centrocusto',
            name='centros_cus_unidade_275ca8_idx',
        ),
        migrations.RemoveField(
            model_name='centrocusto',
            name='orcamento_anual',
        ),
        migrations.RemoveField(
            model_name='centrocusto',
            name='orcamento_mensal',
        ),
        migrations.RemoveField(
            model_name='centrocusto',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='centrocusto',
            name='tipo_operacional',
        ),
        migrations.RemoveField(
            model_name='centrocusto',
            name='unidade',
        ),
    ]
