# Generated by Django 5.1.7 on 2025-09-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_centrocusto_centros_cus_unidade_275ca8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contacontabil',
            name='contas_cont_tipo_co_d07845_idx',
        ),
        migrations.RemoveField(
            model_name='contacontabil',
            name='categoria_dre',
        ),
        migrations.RemoveField(
            model_name='contacontabil',
            name='subcategoria_dre',
        ),
        migrations.RemoveField(
            model_name='contacontabil',
            name='tipo_conta',
        ),
    ]
