# Generated by Django 5.1.7 on 2025-09-04 17:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_contacontabil_contas_cont_tipo_co_d07845_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('diretor', 'Diretor')], default='analista', max_length=20),
        ),
        migrations.CreateModel(
            name='EmpresaCentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_vinculadas', to='core.centrocusto', verbose_name='Centro de Custo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_custo_empresa', to='core.empresa', verbose_name='Empresa')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_custo_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_centro_custo_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Centro de Custo da Empresa',
                'verbose_name_plural': 'Centros de Custo das Empresas',
                'db_table': 'empresa_centros_custo',
                'ordering': ['empresa__sigla', 'centro_custo__codigo'],
                'indexes': [models.Index(fields=['empresa', 'ativo'], name='empresa_cen_empresa_b6434c_idx'), models.Index(fields=['centro_custo', 'ativo'], name='empresa_cen_centro__891f7d_idx'), models.Index(fields=['responsavel'], name='empresa_cen_respons_3b840e_idx'), models.Index(fields=['data_inicio', 'data_fim'], name='empresa_cen_data_in_0c30ca_idx'), models.Index(fields=['ativo'], name='empresa_cen_ativo_63c9c9_idx')],
                'unique_together': {('empresa', 'centro_custo', 'ativo')},
            },
        ),
    ]
