# Generated by Django 5.1.7 on 2025-09-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_usuario_nivel_empresacentrocusto'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='empresacentrocusto',
            name='empresa_cen_data_in_0c30ca_idx',
        ),
        migrations.RemoveField(
            model_name='empresacentrocusto',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='empresacentrocusto',
            name='data_inicio',
        ),
    ]
