# Generated by Django 5.1.7 on 2025-09-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_empresacentrocusto_empresa_cen_data_in_0c30ca_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='tipo',
            field=models.CharField(choices=[('S', 'Sintético'), ('A', 'Analítico')], default='A', max_length=1, verbose_name='Tipo'),
        ),
    ]
