# Generated by Django 5.1.7 on 2025-09-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_migra'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='centrocusto',
            name='centros_cus_centro__ec3b5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='contacontabil',
            name='contas_cont_conta_p_af60cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='unidade',
            name='unidades_unidade_7ed667_idx',
        ),
        migrations.RenameIndex(
            model_name='centrocusto',
            new_name='centros_cus_tipo_d74add_idx',
            old_name='centrocusto_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='contacontabil',
            new_name='contas_cont_tipo_586c75_idx',
            old_name='contacontabil_tipo_idx',
        ),
        migrations.RemoveField(
            model_name='centrocusto',
            name='centro_pai',
        ),
        migrations.RemoveField(
            model_name='contacontabil',
            name='conta_pai',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='unidade_pai',
        ),
    ]
