# Generated by Django 5.1.7 on 2025-09-10 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_centrocusto_centros_cus_centro__ec3b5b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocusto',
            name='tipo',
            field=models.CharField(choices=[('S', 'Sintético'), ('A', 'Analítico')], default='A', help_text='S=Sintético (agrupador), A=Analítico (operacional)', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='tipo',
            field=models.CharField(choices=[('S', 'Sintético'), ('A', 'Analítico')], default='A', help_text='S=Sintético (agrupador), A=Analítico (aceita lançamentos)', max_length=1, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='ContaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_externo', models.CharField(help_text='Código da conta no sistema externo (ERP)', max_length=50, verbose_name='Código Externo')),
                ('nome_externo', models.CharField(help_text='Nome/descrição da conta no sistema externo', max_length=255, verbose_name='Nome no Sistema Externo')),
                ('sistema_origem', models.CharField(blank=True, help_text='Nome do ERP/sistema de origem (ex: Consinco, Protheus)', max_length=100, verbose_name='Sistema de Origem')),
                ('empresas_utilizacao', models.TextField(blank=True, help_text='Empresas que utilizam esta conta (ex: CMC & EBC & Taiff & Action Motors)', verbose_name='Empresas de Utilização')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a conta externa', verbose_name='Observações')),
                ('ativa', models.BooleanField(default=True, help_text='Se a conta externa está ativa', verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('sincronizado', models.BooleanField(default=False, help_text='Se a conta foi sincronizada com o sistema externo', verbose_name='Sincronizado')),
                ('data_ultima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('conta_contabil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_externas', to='core.contacontabil', verbose_name='Conta Contábil Interna')),
            ],
            options={
                'verbose_name': 'Conta Externa',
                'verbose_name_plural': 'Contas Externas',
                'db_table': 'contas_externas',
                'ordering': ['conta_contabil__codigo', 'codigo_externo'],
                'indexes': [models.Index(fields=['conta_contabil'], name='contas_exte_conta_c_582c32_idx'), models.Index(fields=['codigo_externo'], name='contas_exte_codigo__d7eea9_idx'), models.Index(fields=['sistema_origem'], name='contas_exte_sistema_d41db3_idx'), models.Index(fields=['ativa'], name='contas_exte_ativa_f7c987_idx'), models.Index(fields=['sincronizado'], name='contas_exte_sincron_947a59_idx')],
                'unique_together': {('conta_contabil', 'codigo_externo', 'ativa')},
            },
        ),
    ]
