# Generated by Django 5.1.7 on 2025-09-10 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_centrocusto_tipo_alter_contacontabil_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('data', models.DateField(verbose_name='Data do Movimento')),
                ('documento', models.CharField(blank=True, help_text='Número do documento', max_length=50, verbose_name='Documento')),
                ('natureza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito'), ('A', 'Ambas')], help_text='D=Débito, C=Crédito, A=Ambas', max_length=1, verbose_name='Natureza')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do movimento', max_digits=15, verbose_name='Valor')),
                ('historico', models.TextField(help_text='Histórico completo da movimentação', verbose_name='Histórico')),
                ('codigo_projeto', models.CharField(blank=True, max_length=20, verbose_name='Código do Projeto')),
                ('gerador', models.CharField(blank=True, help_text='Sistema ou processo que gerou o movimento', max_length=100, verbose_name='Gerador')),
                ('rateio', models.CharField(default='N', help_text='S=Sim, N=Não', max_length=1, verbose_name='Rateio')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação')),
                ('arquivo_origem', models.CharField(blank=True, help_text='Nome do arquivo Excel de origem', max_length=255, verbose_name='Arquivo de Origem')),
                ('linha_origem', models.IntegerField(blank=True, help_text='Linha no arquivo Excel de origem', null=True, verbose_name='Linha de Origem')),
                ('periodo_mes_ano', models.CharField(db_index=True, help_text='Formato YYYY-MM para indexação rápida', max_length=7, verbose_name='Período')),
                ('valor_absoluto', models.DecimalField(decimal_places=2, help_text='Valor sem sinal para totalizações', max_digits=15, verbose_name='Valor Absoluto')),
            ],
            options={
                'verbose_name': 'Movimento',
                'verbose_name_plural': 'Movimentos',
                'db_table': 'movimentos',
                'ordering': ['-ano', '-mes', '-data', 'id'],
            },
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='data_cadastro',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='inscricao_estadual',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='pix',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='criado_automaticamente',
            field=models.BooleanField(default=False, verbose_name='Criado Automaticamente'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='origem_historico',
            field=models.TextField(blank=True, help_text='Histórico original de onde foi extraído', verbose_name='Histórico de Origem'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ/CPF'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='codigo_allstrategy',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Código All Strategy'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['codigo'], name='fornecedore_codigo_bb168c_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['razao_social'], name='fornecedore_razao_s_c3008e_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['ativo'], name='fornecedore_ativo_bee848_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['criado_automaticamente'], name='fornecedore_criado__b52c13_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['codigo_allstrategy', 'ativa'], name='unidades_codigo__793140_idx'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='centro_custo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.centrocusto', verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='conta_contabil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.contacontabil', verbose_name='Conta Contábil'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Fornecedor extraído do histórico (quando aplicável)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='unidade',
            field=models.ForeignKey(help_text='Unidade organizacional', on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.unidade', verbose_name='Unidade'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['ano', 'mes'], name='movimentos_ano_601055_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['periodo_mes_ano'], name='movimentos_periodo_3e19af_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['data'], name='movimentos_data_60e054_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['unidade'], name='movimentos_unidade_c19ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['centro_custo'], name='movimentos_centro__6a46ee_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['conta_contabil'], name='movimentos_conta_c_9297f1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['fornecedor'], name='movimentos_fornece_b606f6_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['natureza'], name='movimentos_naturez_328a78_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['valor'], name='movimentos_valor_441953_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['ano', 'mes', 'unidade'], name='movimentos_ano_3cd791_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['data_importacao'], name='movimentos_data_im_5ac41c_idx'),
        ),
    ]
