# Generated by Django 5.1.7 on 2025-09-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_movimento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimento',
            options={'ordering': ['-data', '-id'], 'verbose_name': 'Movimento', 'verbose_name_plural': 'Movimentos'},
        ),
        migrations.RemoveIndex(
            model_name='movimento',
            name='movimentos_ano_3cd791_idx',
        ),
        migrations.RemoveIndex(
            model_name='unidade',
            name='unidades_codigo__793140_idx',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='data_ultima_sincronizacao',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='sincronizado_allstrategy',
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='codigo_pai',
            field=models.CharField(blank=True, help_text='Código do centro de custo superior na hierarquia (deixe vazio para raiz)', max_length=20, null=True, verbose_name='Código do Centro Pai'),
        ),
        migrations.AddField(
            model_name='contacontabil',
            name='codigo_pai',
            field=models.CharField(blank=True, help_text='Código da conta contábil superior na hierarquia (deixe vazio para raiz)', max_length=20, null=True, verbose_name='Código da Conta Pai'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='codigo_pai',
            field=models.CharField(blank=True, help_text='Código da unidade superior na hierarquia (deixe vazio para raiz)', max_length=50, null=True, verbose_name='Código da Unidade Pai'),
        ),
        migrations.AlterField(
            model_name='contaexterna',
            name='codigo_externo',
            field=models.CharField(db_index=True, help_text='Código da conta no sistema externo (ERP)', max_length=50, verbose_name='Código Externo'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='razao_social',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='data',
            field=models.DateField(db_index=True, verbose_name='Data do Movimento'),
        ),
        migrations.AddIndex(
            model_name='centrocusto',
            index=models.Index(fields=['codigo_pai'], name='centros_cus_codigo__0a6f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='contacontabil',
            index=models.Index(fields=['codigo_pai'], name='contas_cont_codigo__1d7ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='contaexterna',
            index=models.Index(fields=['codigo_externo', 'ativa'], name='contas_exte_codigo__271330_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['razao_social', 'ativo'], name='fornecedore_razao_s_c0d675_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['data', 'unidade'], name='movimentos_data_f31825_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['arquivo_origem'], name='movimentos_arquivo_9fe715_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['codigo_pai'], name='unidades_codigo__ae00c8_idx'),
        ),
    ]
