# Generated by Django 5.1.7 on 2025-10-29 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_movimento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contaexterna',
            options={'ordering': ['conta_contabil__codigo', 'codigo_externo'], 'verbose_name': 'Código ERP', 'verbose_name_plural': 'Códigos ERP'},
        ),
        migrations.AlterField(
            model_name='contaexterna',
            name='ativa',
            field=models.BooleanField(default=True, help_text='Se a conta do ERP está ativa', verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='contaexterna',
            name='codigo_externo',
            field=models.CharField(db_index=True, help_text='Código da conta no sistema ERP', max_length=50, verbose_name='Código ERP'),
        ),
        migrations.AlterField(
            model_name='contaexterna',
            name='nome_externo',
            field=models.CharField(help_text='Nome/descrição da conta no sistema ERP', max_length=255, verbose_name='Nome no ERP'),
        ),
        migrations.AlterField(
            model_name='contaexterna',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações sobre a conta do ERP', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='contaexterna',
            name='sincronizado',
            field=models.BooleanField(default=False, help_text='Se a conta foi sincronizada com o sistema ERP', verbose_name='Sincronizado'),
        ),
        migrations.CreateModel(
            name='CentroCustoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_externo', models.CharField(db_index=True, help_text='Código do centro de custo no sistema ERP', max_length=50, verbose_name='Código ERP')),
                ('nome_externo', models.CharField(help_text='Nome/descrição do centro de custo no sistema ERP', max_length=255, verbose_name='Nome no ERP')),
                ('sistema_origem', models.CharField(blank=True, help_text='Nome do ERP/sistema de origem (ex: Consinco, Protheus)', max_length=100, verbose_name='Sistema de Origem')),
                ('empresas_utilizacao', models.TextField(blank=True, help_text='Empresas que utilizam este centro de custo (ex: CMC & EBC & Taiff & Action Motors)', verbose_name='Empresas de Utilização')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o centro de custo do ERP', verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, help_text='Se o centro de custo do ERP está ativo', verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('sincronizado', models.BooleanField(default=False, help_text='Se o centro de custo foi sincronizado com o sistema ERP', verbose_name='Sincronizado')),
                ('data_ultima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_externos', to='core.centrocusto', verbose_name='Centro de Custo Interno')),
            ],
            options={
                'verbose_name': 'Código ERP Centro de Custo',
                'verbose_name_plural': 'Códigos ERP Centros de Custo',
                'db_table': 'centros_custo_externos',
                'ordering': ['centro_custo__codigo', 'codigo_externo'],
                'indexes': [models.Index(fields=['centro_custo'], name='centros_cus_centro__f91eb4_idx'), models.Index(fields=['codigo_externo'], name='centros_cus_codigo__f99068_idx'), models.Index(fields=['sistema_origem'], name='centros_cus_sistema_f6b2b0_idx'), models.Index(fields=['ativo'], name='centros_cus_ativo_8be9a3_idx'), models.Index(fields=['sincronizado'], name='centros_cus_sincron_71ed53_idx'), models.Index(fields=['codigo_externo', 'ativo'], name='centros_cus_codigo__ac84a3_idx')],
                'unique_together': {('centro_custo', 'codigo_externo', 'ativo')},
            },
        ),
    ]
