# Generated by Django 5.1.7 on 2025-11-02 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_centrocustoexterno_responsavel_beneficiado'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoFornecedor',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código')),
                ('nome', models.CharField(db_index=True, max_length=255, verbose_name='Nome do Grupo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do grupo de fornecedores', verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo de Fornecedor',
                'verbose_name_plural': 'Grupos de Fornecedores',
                'db_table': 'grupos_fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.RenameIndex(
            model_name='centrocustoexterno',
            new_name='centros_cus_codigo__d3d82c_idx',
            old_name='centros_cus_codigo__resp_idx',
        ),
        migrations.RenameIndex(
            model_name='centrocustoexterno',
            new_name='centros_cus_codigo__29b639_idx',
            old_name='centros_cus_codigo__benef_idx',
        ),
        migrations.RenameIndex(
            model_name='contacontabil',
            new_name='contas_cont_relator_ee88de_idx',
            old_name='contas_cont_relator_idx',
        ),
        migrations.RenameIndex(
            model_name='grupocc',
            new_name='grupos_cc_codigo_09ff5f_idx',
            old_name='grupos_cc_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='grupocc',
            new_name='grupos_cc_ativa_8c19bb_idx',
            old_name='grupos_cc_ativa_idx',
        ),
        migrations.AddIndex(
            model_name='grupofornecedor',
            index=models.Index(fields=['codigo'], name='grupos_forn_codigo_33fdc3_idx'),
        ),
        migrations.AddIndex(
            model_name='grupofornecedor',
            index=models.Index(fields=['nome'], name='grupos_forn_nome_52e980_idx'),
        ),
        migrations.AddIndex(
            model_name='grupofornecedor',
            index=models.Index(fields=['ativo'], name='grupos_forn_ativo_01b7b8_idx'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Grupo ao qual este fornecedor pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores', to='core.grupofornecedor', verbose_name='Grupo'),
        ),
    ]
